spring:
  profiles:
    active: prod
othr:
  auth: http://im-codd.oth-regensburg.de:8931
  warehouse:
    host: http://im-codd.oth-regensburg.de:8950
    customer-number: "00000001"
  drinks-on-demand:
    host: http://im-codd.oth-regensburg.de:8947
    customer-id: 93d70a8a-3a52-456e-864e-870393774d81
