spring:
  datasource:
    url: jdbc:mysql://im-knuth.oth-regensburg.de:3306/sw_benjamin_eder
    driver-class-name: com.mysql.jdbc.Driver
    username: sw_benjamin_eder
    password: edb43740
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8939
