name: Build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master, release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14
      - name: Compile
        run: ./mvnw clean compile
      - name: Test
        run: ./mvnw clean test
      - name: Package
        run: ./mvnw clean package spring-boot:repackage -Dmaven.test.skip=true
      - name: Upload Server Jar
        uses: actions/upload-artifact@v2.2.2
        with:
          name: sw-barmanagement
          path: ./target/sw-barmanagement-*.jar
